"""empty message

Revision ID: 6d073377f769
Revises: 
Create Date: 2020-11-02 15:58:59.902554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d073377f769'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('emprestimos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_emprestimo', sa.DateTime(), nullable=True),
    sa.Column('data_previsao_entrega', sa.DateTime(), nullable=True),
    sa.Column('data_entrega', sa.DateTime(), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('vol', sa.Integer(), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.Column('emprestimo_id', sa.Integer(), nullable=True),
    sa.Column('adicionado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emprestimo_id'], ['emprestimos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autor_livro',
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('livro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['autores.id'], ),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autor_livro')
    op.drop_table('livros')
    op.drop_table('emprestimos')
    op.drop_table('usuarios')
    op.drop_table('autores')
    # ### end Alembic commands ###
